version: "3"
networks:
  pandora:
    name: pandora
    driver: bridge
    external: false    
services:
  pandora-meuonibuslogger-api:
    image: stgutem/pandora-meuonibuslogger:latest
    container_name: pandora-meuonibuslogger
    ports:
      - ${APP_PORT}:3000
    environment:
      - PG_HOST=${POSTGRES_HOST}
      - PG_USER=${POSTGRES_USERNAME}
      - PG_PASS=${POSTGRES_PASSWORD}
      - PG_DB=${POSTGRES_DATABASE}
      - PG_PORT=${POSTGRES_PORT}
      - TELEGRAM_BOT_TOKEN=${BOT_TOKEN}
      - BACKUP_TOKEN=${BACKUP_TOKEN}
      - TZ=America/Fortaleza
    networks:
      - pandora
    volumes:
      - ${DATA_PATH}:/app/.data
    restart: unless-stopped