version: "3"
networks:
  pandora:
    external: false    
services:
  pandora-controller-api:
    image: stgutem/pandora-controller
    container_name: pandora-controller
    ports:
      - 4000:3000
    environment:
      - PG_HOST=${POSTGRES_HOST}
      - PG_USER=${POSTGRES_USERNAME}
      - PG_PASS=${POSTGRES_PASSWORD}
      - PG_DB=${POSTGRES_DATABASE}
      - PG_PORT=${POSTGRES_PORT}
      - TELEGRAM_BOT_TOKEN=${BOT_TOKEN}
      - BACKUP_TOKEN=${BACKUP_TOKEN}
    networks:
      - pandora
    volumes:
      - ${DATA_PATH}:/app/.data
    restart: unless-stopped